import { StyleSheet } from "react-native";

export const Typography = StyleSheet.create({
  h1: {
    fontFamily: "Roboto",
    fontWeight: "700",
    fontSize: 40,
    lineHeight: 44,
    letterSpacing: -0.4,
  },
  homeTitle: {
    fontFamily: "Roboto",
    fontWeight: "700",
    fontSize: 28,
    lineHeight: 30.8,
    letterSpacing: -0.4,
  },
  verseText: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 25.2,
    letterSpacing: -0.4,
  },
  h2: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 24,
    lineHeight: 26.4,
    letterSpacing: -0.4,
  },
  h3: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: -0.4,
  },
  subheading: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 19.8,
    letterSpacing: -0.4,
  },
  bodySemibold: {
    fontFamily: "Roboto",
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 17.6,
    letterSpacing: -0.4,
  },
  bodyMedium: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 18.75,
  },
  bodyRegular: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 17.6,
    letterSpacing: -0.4,
  },
  smallBold: {
    fontFamily: "Roboto",
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: -0.4,
  },
  smallMedium: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 19.6,
    letterSpacing: -0.4,
  },
  smallRegular: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 15.4,
    letterSpacing: -0.4,
  },
  extraSmall: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 22,
  },
  sessionCardElem: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 16.41,
  },
  sessionCardDate: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 14.06,
  },
  ModalTitle: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 22,
    letterSpacing: -0.4,
  },
});
